导入numpy和pandas库

In [2]:
import numpy as np
import pandas as pd

导入航班延误的csv文件flights.csv,并将date列的数据类型转化为str,如果不显示转化，则显示的会去掉前面的0，整数形式

In [3]:
df = pd.read_csv("flights.csv",dtype={'date':str})
df.head()

       date  delay  distance origin destination
0  02221605      3       358    BUR         SMF
1  01022100     -5       239    HOU         DAL
2  03210808      6       288    BWI         ALB
3  02042155    -15       313    MCI         OKC
4  01031304     23       935    PHX         TUL

查看行列数

In [13]:
df.shape

(1000, 5)

查看所有的列的数据类型

In [8]:
df.dtypes

date           object
delay           int64
distance        int64
origin         object
destination    object
dtype: object

查看数据信息df.info()

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
date           1000 non-null object
delay          1000 non-null int64
distance       1000 non-null int64
origin         1000 non-null object
destination    1000 non-null object
dtypes: int64(2), object(3)
memory usage: 27.4+ KB

## 选择列

In [23]:
df[['date']]

         date
0    02221605
1    01022100
2    03210808
3    02042155
4    01031304
5    01022052
6    01181550
7    03041110
8    01041210
9    01241612
10   02141813
11   03212145
12   02220830
13   03281220
14   03060605
15   03151759
16   02041310
17   02031625
18   03231610
19   02221938
20   03281355
21   02141407
22   02252025
23   02181325
24   02211140
25   02261810
26   03300755
27   01282020
28   01181812
29   02252107
..        ...
970  02191933
971  01141930
972  01191610
973  03310640
974  01111220
975  02171326
976  03290945
977  03261518
978  03011942
979  01160800
980  03240755
981  01151743
982  01112000
983  02171608
984  01210700
985  03042153
986  02032025
987  03251505
988  03011923
989  01101735
990  01211025
991  02221110
992  03261640
993  03082125
994  03051333
995  03011440
996  03101325
997  03170830
998  01041339
999  01171057

[1000 rows x 1 columns]

In [25]:
df[['date', 'delay']]

         date  delay
0    02221605      3
1    01022100     -5
2    03210808      6
3    02042155    -15
4    01031304     23
5    01022052     26
6    01181550      2
7    03041110     -3
8    01041210    -30
9    01241612      0
10   02141813     28
11   03212145    -10
12   02220830     -5
13   03281220     -2
14   03060605     -7
15   03151759     36
16   02041310      0
17   02031625     -9
18   03231610    -19
19   02221938     18
20   03281355     -2
21   02141407     13
22   02252025     45
23   02181325      2
24   02211140      5
25   02261810      0
26   03300755     -3
27   01282020     -4
28   01181812     71
29   02252107     14
..        ...    ...
970  02191933    136
971  01141930      8
972  01191610     -2
973  03310640    -10
974  01111220     -8
975  02171326      4
976  03290945     12
977  03261518     25
978  03011942     -2
979  01160800      8
980  03240755     -2
981  01151743     18
982  01112000     40
983  02171608     20
984  01210700    -10
985  03042153      5
986  02032025      5
987  03251505      5
988  03011923     20
989  01101735      5
990  01211025    -13
991  02221110     -4
992  03261640     -6
993  03082125    113
994  03051333     -8
995  03011440     13
996  03101325     -5
997  03170830     20
998  01041339     20
999  01171057     18

[1000 rows x 2 columns]

In [26]:
df.loc[10:100, ['date', 'delay']]

         date  delay
10   02141813     28
11   03212145    -10
12   02220830     -5
13   03281220     -2
14   03060605     -7
15   03151759     36
16   02041310      0
17   02031625     -9
18   03231610    -19
19   02221938     18
20   03281355     -2
21   02141407     13
22   02252025     45
23   02181325      2
24   02211140      5
25   02261810      0
26   03300755     -3
27   01282020     -4
28   01181812     71
29   02252107     14
30   03241238      8
31   02242143     35
32   01231415      0
33   01230630      5
34   03241230     11
35   01201400     -4
36   03221515     16
37   03060640      8
38   03182149     13
39   03180930     10
..        ...    ...
71   01191448      8
72   01291900     35
73   03141330    -17
74   03162123     35
75   02040900     -8
76   01201835     -7
77   01031310     44
78   01211308     16
79   01221330    -11
80   01161440    -10
81   03291815     -1
82   02161016      0
83   02192010      0
84   01261514     46
85   02011954      0
86   02091350     10
87   01191527     10
88   02210850     -5
89   03031612     17
90   01211200    -13
91   02251920     -2
92   01131030     -3
93   01090730      0
94   02251405     48
95   03221745     -5
96   03181224     22
97   01191230    -15
98   03301415     -2
99   02270940     -2
100  03150755     -1

[91 rows x 2 columns]

字符串函数使用，Pandas 的字符串函数可以通过 DateFrame 和 Series 的 str 属性来调用，如 df['origin'].str.lower()

In [29]:
df['origin'].str.cat(df['destination'], sep=' to ')

0      BUR to SMF
1      HOU to DAL
2      BWI to ALB
3      MCI to OKC
4      PHX to TUL
5      MCI to LAX
6      BUR to LAS
7      MSY to BHM
8      BDL to BNA
9      PDX to SMF
10     MDW to MCI
11     BUR to LAS
12     HOU to TUL
13     OAK to PHX
14     PDX to SJC
15     BDL to BWI
16     OAK to RNO
17     BUR to SJC
18     MCI to LAX
19     HOU to HRL
20     MCI to BNA
21     STL to MDW
22     LIT to DAL
23     MCI to MDW
24     STL to MDW
25     LAX to ELP
26     BUR to SMF
27     SAN to SJC
28     BUR to OAK
29     DAL to SAT
          ...
970    OAK to LAX
971    MCI to MHT
972    MAF to DAL
973    SLC to PHX
974    ELP to SAT
975    SEA to OAK
976    BNA to MSY
977    BWI to ISP
978    ISP to PVD
979    BWI to ALB
980    LAS to LAX
981    BWI to TPA
982    STL to MDW
983    SAN to OAK
984    LAS to SAN
985    SLC to PHX
986    BWI to MCO
987    ELP to LAX
988    MSY to BNA
989    BWI to IND
990    MDW to IND
991    BUR to SMF
992    LAS to HOU
993    OAK to RNO
994    SNA to SJC
995    ABQ to DAL
996    BOI to RNO
997    BNA to PHX
998    PHX to SEA
999    SAT to HOU
Name: origin, Length: 1000, dtype: object

In [4]:
df['origin'].str.strip()#去字符串的空格

0      BUR
1      HOU
2      BWI
3      MCI
4      PHX
5      MCI
6      BUR
7      MSY
8      BDL
9      PDX
10     MDW
11     BUR
12     HOU
13     OAK
14     PDX
15     BDL
16     OAK
17     BUR
18     MCI
19     HOU
20     MCI
21     STL
22     LIT
23     MCI
24     STL
25     LAX
26     BUR
27     SAN
28     BUR
29     DAL
      ...
970    OAK
971    MCI
972    MAF
973    SLC
974    ELP
975    SEA
976    BNA
977    BWI
978    ISP
979    BWI
980    LAS
981    BWI
982    STL
983    SAN
984    LAS
985    SLC
986    BWI
987    ELP
988    MSY
989    BWI
990    MDW
991    BUR
992    LAS
993    OAK
994    SNA
995    ABQ
996    BOI
997    BNA
998    PHX
999    SAT
Name: origin, Length: 1000, dtype: object

In [5]:
df['origin'].str.replace('a', 'b')

0      BUR
1      HOU
2      BWI
3      MCI
4      PHX
5      MCI
6      BUR
7      MSY
8      BDL
9      PDX
10     MDW
11     BUR
12     HOU
13     OAK
14     PDX
15     BDL
16     OAK
17     BUR
18     MCI
19     HOU
20     MCI
21     STL
22     LIT
23     MCI
24     STL
25     LAX
26     BUR
27     SAN
28     BUR
29     DAL
      ...
970    OAK
971    MCI
972    MAF
973    SLC
974    ELP
975    SEA
976    BNA
977    BWI
978    ISP
979    BWI
980    LAS
981    BWI
982    STL
983    SAN
984    LAS
985    SLC
986    BWI
987    ELP
988    MSY
989    BWI
990    MDW
991    BUR
992    LAS
993    OAK
994    SNA
995    ABQ
996    BOI
997    BNA
998    PHX
999    SAT
Name: origin, Length: 1000, dtype: object

In [6]:
df['origin'].str[0:1]

0      B
1      H
2      B
3      M
4      P
5      M
6      B
7      M
8      B
9      P
10     M
11     B
12     H
13     O
14     P
15     B
16     O
17     B
18     M
19     H
20     M
21     S
22     L
23     M
24     S
25     L
26     B
27     S
28     B
29     D
      ..
970    O
971    M
972    M
973    S
974    E
975    S
976    B
977    B
978    I
979    B
980    L
981    B
982    S
983    S
984    L
985    S
986    B
987    E
988    M
989    B
990    M
991    B
992    L
993    O
994    S
995    A
996    B
997    B
998    P
999    S
Name: origin, Length: 1000, dtype: object

### WHERE - 选择行

In [11]:
(df['delay']>0).head()

0     True
1    False
2     True
3    False
4     True
Name: delay, dtype: bool

In [13]:
df[(df['delay']>0)].head()

       date  delay  distance origin destination
0  02221605      3       358    BUR         SMF
2  03210808      6       288    BWI         ALB
4  01031304     23       935    PHX         TUL
5  01022052     26      1363    MCI         LAX
6  01181550      2       223    BUR         LAS

In [16]:
df[(df['delay']>0)&(df['distance'] > 300)]

         date  delay  distance origin destination
0    02221605      3       358    BUR         SMF
4    01031304     23       935    PHX         TUL
5    01022052     26      1363    MCI         LAX
10   02141813     28       405    MDW         MCI
23   02181325      2       405    MCI         MDW
28   01181812     71       325    BUR         OAK
31   02242143     35       328    BWI         PVD
33   01230630      5       325    PHX         ONT
34   03241230     11       407    LAS         OAK
36   03221515     16       337    LAX         OAK
38   03182149     13       325    ONT         PHX
39   03180930     10      1140    LAS         MCI
41   02261255      8       628    ABQ         SAN
45   03161941      9      1090    LAS         AUS
46   01162309     75       621    SJC         PHX
47   01281620      3       308    LAX         SJC
50   01100615      5       399    SEA         BOI
53   01241217     22       325    BUR         OAK
56   03161733     37       417    SAN         SJC
63   02072027      6       308    SJC         LAX
64   01191122      6       325    OAK         BUR
65   02230838     40      1407    BWI         SAT
66   02071928      3       325    ONT         PHX
67   02251805     28       671    SEA         OAK
68   03012010      5       714    LAX         ELP
71   01191448      8       325    OAK         BUR
74   03162123     35       480    SAN         SMF
77   01031310     44      1262    PHX         STL
78   01211308     16       308    SJC         LAX
84   01261514     46       580    ABQ         DAL
..        ...    ...       ...    ...         ...
926  02261958      5      1489    MCI         OAK
930  02141720      3       520    LAS         BOI
934  01111150     10       304    PHX         SAN
936  03161838     83       550    MSY         MCO
939  01161410      5       491    MCI         BNA
949  01170615     10       453    TUL         HOU
952  03161325      6       389    ONT         SMF
954  02131252     52       393    HOU         LIT
955  01022150     51       480    SMF         SAN
956  02201040      8       708    IND         MSY
957  03041800      4       410    CMH         STL
961  03061750     25       423    OMA         MDW
963  03241544     13       423    OMA         MDW
965  02040740     22       308    SJC         LAX
968  02141633     25       833    PHX         OKC
969  03152015     33       419    HOU         OKC
970  02191933    136       337    OAK         LAX
971  01141930      8      1236    MCI         MHT
975  02171326      4       671    SEA         OAK
976  03290945     12       471    BNA         MSY
981  01151743     18       842    BWI         TPA
983  02171608     20       446    SAN         OAK
985  03042153      5       507    SLC         PHX
986  02032025      5       787    BWI         MCO
987  03251505      5       714    ELP         LAX
988  03011923     20       471    MSY         BNA
989  01101735      5       515    BWI         IND
995  03011440     13       580    ABQ         DAL
997  03170830     20      1448    BNA         PHX
998  01041339     20      1107    PHX         SEA

[345 rows x 5 columns]

In [17]:
df[(df['delay']> 0)| (df['origin'] == 'BUR')]

         date  delay  distance origin destination
0    02221605      3       358    BUR         SMF
2    03210808      6       288    BWI         ALB
4    01031304     23       935    PHX         TUL
5    01022052     26      1363    MCI         LAX
6    01181550      2       223    BUR         LAS
10   02141813     28       405    MDW         MCI
11   03212145    -10       223    BUR         LAS
15   03151759     36       283    BDL         BWI
17   02031625     -9       296    BUR         SJC
19   02221938     18       276    HOU         HRL
21   02141407     13       251    STL         MDW
22   02252025     45       296    LIT         DAL
23   02181325      2       405    MCI         MDW
24   02211140      5       251    STL         MDW
26   03300755     -3       358    BUR         SMF
28   01181812     71       325    BUR         OAK
29   02252107     14       248    DAL         SAT
30   03241238      8       239    HOU         DAL
31   02242143     35       328    BWI         PVD
33   01230630      5       325    PHX         ONT
34   03241230     11       407    LAS         OAK
36   03221515     16       337    LAX         OAK
37   03060640      8       188    SJC         RNO
38   03182149     13       325    ONT         PHX
39   03180930     10      1140    LAS         MCI
40   01261250     27       197    ONT         LAS
41   02261255      8       628    ABQ         SAN
42   02152208     65       197    TPA         FLL
43   02050640     19       288    ALB         BWI
45   03161941      9      1090    LAS         AUS
..        ...    ...       ...    ...         ...
954  02131252     52       393    HOU         LIT
955  01022150     51       480    SMF         SAN
956  02201040      8       708    IND         MSY
957  03041800      4       410    CMH         STL
960  01271420      2       283    BWI         BDL
961  03061750     25       423    OMA         MDW
963  03241544     13       423    OMA         MDW
965  02040740     22       308    SJC         LAX
968  02141633     25       833    PHX         OKC
969  03152015     33       419    HOU         OKC
970  02191933    136       337    OAK         LAX
971  01141930      8      1236    MCI         MHT
975  02171326      4       671    SEA         OAK
976  03290945     12       471    BNA         MSY
977  03261518     25       220    BWI         ISP
979  01160800      8       288    BWI         ALB
981  01151743     18       842    BWI         TPA
982  01112000     40       251    STL         MDW
983  02171608     20       446    SAN         OAK
985  03042153      5       507    SLC         PHX
986  02032025      5       787    BWI         MCO
987  03251505      5       714    ELP         LAX
988  03011923     20       471    MSY         BNA
989  01101735      5       515    BWI         IND
991  02221110     -4       358    BUR         SMF
993  03082125    113       180    OAK         RNO
995  03011440     13       580    ABQ         DAL
997  03170830     20      1448    BNA         PHX
998  01041339     20      1107    PHX         SEA
999  01171057     18       192    SAT         HOU

[485 rows x 5 columns]

In [18]:
df[df['delay'].isnull()]

Empty DataFrame
Columns: [date, delay, distance, origin, destination]
Index: []

In [20]:
df[df['delay'].notnull()]

         date  delay  distance origin destination
0    02221605      3       358    BUR         SMF
1    01022100     -5       239    HOU         DAL
2    03210808      6       288    BWI         ALB
3    02042155    -15       313    MCI         OKC
4    01031304     23       935    PHX         TUL
5    01022052     26      1363    MCI         LAX
6    01181550      2       223    BUR         LAS
7    03041110     -3       321    MSY         BHM
8    01041210    -30       852    BDL         BNA
9    01241612      0       479    PDX         SMF
10   02141813     28       405    MDW         MCI
11   03212145    -10       223    BUR         LAS
12   02220830     -5       453    HOU         TUL
13   03281220     -2       646    OAK         PHX
14   03060605     -7       569    PDX         SJC
15   03151759     36       283    BDL         BWI
16   02041310      0       180    OAK         RNO
17   02031625     -9       296    BUR         SJC
18   03231610    -19      1363    MCI         LAX
19   02221938     18       276    HOU         HRL
20   03281355     -2       491    MCI         BNA
21   02141407     13       251    STL         MDW
22   02252025     45       296    LIT         DAL
23   02181325      2       405    MCI         MDW
24   02211140      5       251    STL         MDW
25   02261810      0       714    LAX         ELP
26   03300755     -3       358    BUR         SMF
27   01282020     -4       417    SAN         SJC
28   01181812     71       325    BUR         OAK
29   02252107     14       248    DAL         SAT
..        ...    ...       ...    ...         ...
970  02191933    136       337    OAK         LAX
971  01141930      8      1236    MCI         MHT
972  01191610     -2       319    MAF         DAL
973  03310640    -10       507    SLC         PHX
974  01111220     -8       496    ELP         SAT
975  02171326      4       671    SEA         OAK
976  03290945     12       471    BNA         MSY
977  03261518     25       220    BWI         ISP
978  03011942     -2       108    ISP         PVD
979  01160800      8       288    BWI         ALB
980  03240755     -2       236    LAS         LAX
981  01151743     18       842    BWI         TPA
982  01112000     40       251    STL         MDW
983  02171608     20       446    SAN         OAK
984  01210700    -10       258    LAS         SAN
985  03042153      5       507    SLC         PHX
986  02032025      5       787    BWI         MCO
987  03251505      5       714    ELP         LAX
988  03011923     20       471    MSY         BNA
989  01101735      5       515    BWI         IND
990  01211025    -13       162    MDW         IND
991  02221110     -4       358    BUR         SMF
992  03261640     -6      1235    LAS         HOU
993  03082125    113       180    OAK         RNO
994  03051333     -8       342    SNA         SJC
995  03011440     13       580    ABQ         DAL
996  03101325     -5       335    BOI         RNO
997  03170830     20      1448    BNA         PHX
998  01041339     20      1107    PHX         SEA
999  01171057     18       192    SAT         HOU

[1000 rows x 5 columns]

In [24]:
df.query('delay > 0 and distance <= 500')

         date  delay  distance origin destination
0    02221605      3       358    BUR         SMF
2    03210808      6       288    BWI         ALB
6    01181550      2       223    BUR         LAS
10   02141813     28       405    MDW         MCI
15   03151759     36       283    BDL         BWI
19   02221938     18       276    HOU         HRL
21   02141407     13       251    STL         MDW
22   02252025     45       296    LIT         DAL
23   02181325      2       405    MCI         MDW
24   02211140      5       251    STL         MDW
28   01181812     71       325    BUR         OAK
29   02252107     14       248    DAL         SAT
30   03241238      8       239    HOU         DAL
31   02242143     35       328    BWI         PVD
33   01230630      5       325    PHX         ONT
34   03241230     11       407    LAS         OAK
36   03221515     16       337    LAX         OAK
37   03060640      8       188    SJC         RNO
38   03182149     13       325    ONT         PHX
40   01261250     27       197    ONT         LAS
42   02152208     65       197    TPA         FLL
43   02050640     19       288    ALB         BWI
47   01281620      3       308    LAX         SJC
50   01100615      5       399    SEA         BOI
53   01241217     22       325    BUR         OAK
56   03161733     37       417    SAN         SJC
63   02072027      6       308    SJC         LAX
64   01191122      6       325    OAK         BUR
66   02071928      3       325    ONT         PHX
71   01191448      8       325    OAK         BUR
..        ...    ...       ...    ...         ...
905  01071518     19       446    SAN         OAK
906  03242100     15       405    MCI         MDW
910  03021208      6       162    IND         MDW
916  02260940      3       319    MAF         DAL
919  02250900      4       370    LAX         PHX
925  02250625      5       451    TUS         LAX
928  02251726      7       187    HOU         CRP
931  02211815      5       223    ELP         ABQ
934  01111150     10       304    PHX         SAN
939  01161410      5       491    MCI         BNA
944  02191311     13       276    HRL         HOU
949  01170615     10       453    TUL         HOU
952  03161325      6       389    ONT         SMF
954  02131252     52       393    HOU         LIT
955  01022150     51       480    SMF         SAN
957  03041800      4       410    CMH         STL
960  01271420      2       283    BWI         BDL
961  03061750     25       423    OMA         MDW
963  03241544     13       423    OMA         MDW
965  02040740     22       308    SJC         LAX
969  03152015     33       419    HOU         OKC
970  02191933    136       337    OAK         LAX
976  03290945     12       471    BNA         MSY
977  03261518     25       220    BWI         ISP
979  01160800      8       288    BWI         ALB
982  01112000     40       251    STL         MDW
983  02171608     20       446    SAN         OAK
988  03011923     20       471    MSY         BNA
993  03082125    113       180    OAK         RNO
999  01171057     18       192    SAT         HOU

[325 rows x 5 columns]

In [25]:
df.query('(delay > 0) | (origin == "BUR")')

         date  delay  distance origin destination
0    02221605      3       358    BUR         SMF
2    03210808      6       288    BWI         ALB
4    01031304     23       935    PHX         TUL
5    01022052     26      1363    MCI         LAX
6    01181550      2       223    BUR         LAS
10   02141813     28       405    MDW         MCI
11   03212145    -10       223    BUR         LAS
15   03151759     36       283    BDL         BWI
17   02031625     -9       296    BUR         SJC
19   02221938     18       276    HOU         HRL
21   02141407     13       251    STL         MDW
22   02252025     45       296    LIT         DAL
23   02181325      2       405    MCI         MDW
24   02211140      5       251    STL         MDW
26   03300755     -3       358    BUR         SMF
28   01181812     71       325    BUR         OAK
29   02252107     14       248    DAL         SAT
30   03241238      8       239    HOU         DAL
31   02242143     35       328    BWI         PVD
33   01230630      5       325    PHX         ONT
34   03241230     11       407    LAS         OAK
36   03221515     16       337    LAX         OAK
37   03060640      8       188    SJC         RNO
38   03182149     13       325    ONT         PHX
39   03180930     10      1140    LAS         MCI
40   01261250     27       197    ONT         LAS
41   02261255      8       628    ABQ         SAN
42   02152208     65       197    TPA         FLL
43   02050640     19       288    ALB         BWI
45   03161941      9      1090    LAS         AUS
..        ...    ...       ...    ...         ...
954  02131252     52       393    HOU         LIT
955  01022150     51       480    SMF         SAN
956  02201040      8       708    IND         MSY
957  03041800      4       410    CMH         STL
960  01271420      2       283    BWI         BDL
961  03061750     25       423    OMA         MDW
963  03241544     13       423    OMA         MDW
965  02040740     22       308    SJC         LAX
968  02141633     25       833    PHX         OKC
969  03152015     33       419    HOU         OKC
970  02191933    136       337    OAK         LAX
971  01141930      8      1236    MCI         MHT
975  02171326      4       671    SEA         OAK
976  03290945     12       471    BNA         MSY
977  03261518     25       220    BWI         ISP
979  01160800      8       288    BWI         ALB
981  01151743     18       842    BWI         TPA
982  01112000     40       251    STL         MDW
983  02171608     20       446    SAN         OAK
985  03042153      5       507    SLC         PHX
986  02032025      5       787    BWI         MCO
987  03251505      5       714    ELP         LAX
988  03011923     20       471    MSY         BNA
989  01101735      5       515    BWI         IND
991  02221110     -4       358    BUR         SMF
993  03082125    113       180    OAK         RNO
995  03011440     13       580    ABQ         DAL
997  03170830     20      1448    BNA         PHX
998  01041339     20      1107    PHX         SEA
999  01171057     18       192    SAT         HOU

[485 rows x 5 columns]

## GROUP BY - 汇总

In [26]:
df.groupby('origin').size()

origin
ABQ    22
ALB     4
AMA     4
AUS    10
BDL     8
BHM    11
BNA    43
BOI     8
BUF     5
BUR    27
BWI    49
CLE     6
CMH     6
CRP     3
DAL    42
DTW    10
ELP    16
FLL     7
GEG     4
HOU    41
HRL     6
IAH     4
IND    11
ISP    12
JAN     2
JAX     5
LAS    64
LAX    48
LBB     3
LIT     5
MAF     7
MCI    34
MCO    18
MDW    49
MHT     3
MSY    25
OAK    38
OKC    11
OMA    11
ONT    14
PBI     5
PDX    15
PHX    64
PVD     7
RDU     5
RNO     6
SAN    25
SAT    17
SDF     2
SEA    18
SFO     2
SJC    28
SLC    17
SMF    22
SNA    12
STL    30
TPA    15
TUL     9
TUS     5
dtype: int64

In [27]:
df.groupby(['origin', 'destination']).agg({
    'delay': np.sum,
    'distance': np.mean
})

                    delay  distance
origin destination
ABQ    DAL             68       580
       ELP            -10       223
       HOU             44       759
       LAS             49       487
       LAX             30       677
       MCO             -5      1552
       PHX            -22       328
       SAN             13       628
       STL            -13       934
       TUS             -3       321
ALB    BWI              7       288
       LAS            -32      2237
       MCO            -10      1073
AMA    ABQ              5       277
       DAL             -9       324
AUS    DAL             10       189
       HOU            -10       148
       LAS             -8      1090
       MAF            -10       294
       PHX              0       872
       RDU             60      1162
BDL    BNA            -38       852
       BWI             81       283
       MDW              4       777
BHM    BNA            -12       177
       MCO            -10       478
       MDW              3       570
       MSY             61       321
       SDF             11       323
       TPA             -9       460
...                   ...       ...
STL    BHM             -1       410
       CLE             37       487
       CMH             12       410
       DTW             -4       440
       HOU             44       687
       IND              7       229
       LIT            -17       296
       MCI             -6       237
       MDW             58       251
       OMA            -14       342
       PHX             11      1262
       SDF            104       254
TPA    ABQ            -22      1497
       BNA            -11       612
       BWI             68       842
       FLL            163       197
       IND              5       838
       JAX             13       180
       MCI             -2      1048
       MDW             -8       997
       MSY             -1       487
       PBI            -10       174
       RDU             -2       587
TUL    DAL            176       237
       HOU             10       453
       MCI             -1       223
       STL             72       351
TUS    LAS              1       365
       LAX             11       451
       SAN             -6       367

[409 rows x 2 columns]

In [28]:
df.groupby('origin')['delay'].agg(['min', 'max'])

        min  max
origin
ABQ     -13   54
ALB     -32   19
AMA      -6    5
AUS     -40  100
BDL     -30   36
BHM     -12   62
BNA     -19  113
BOI     -12   44
BUF     -15   14
BUR     -10   71
BWI     -17  100
CLE     -15   46
CMH     -10    4
CRP      -2   14
DAL      -7   74
DTW     -10   47
ELP     -10   75
FLL      -6    0
GEG     -14   22
HOU     -18   85
HRL      -6   13
IAH      -2   63
IND     -15   13
ISP     -17   67
JAN      -5    0
JAX     -34    0
LAS     -32  103
LAX     -13  117
LBB       0   10
LIT      -7   65
MAF      -5   11
MCI     -19  102
MCO     -19   93
MDW     -25   85
MHT      -2   28
MSY     -15   83
OAK     -15  136
OKC     -25    8
OMA     -26   25
ONT     -22   45
PBI      -5   14
PDX     -10   21
PHX     -18  162
PVD     -10   41
RDU      -7   -1
RNO     -15    5
SAN     -15  135
SAT     -14   18
SDF      -1    4
SEA     -18  110
SFO      -1    3
SJC     -17   99
SLC     -13  135
SMF     -15   60
SNA      -8   15
STL     -14   62
TPA     -22   68
TUL      -6  165
TUS      -7    8

In [29]:
df.set_index('origin').groupby(len).size()

3    1000
dtype: int64

## ORDER BY - 排序

In [30]:
df.set_index('origin').sort_index()

            date  delay  distance destination
origin
ABQ     03201840    -10       328         PHX
ABQ     01220705    -10       223         ELP
ABQ     02261255      8       628         SAN
ABQ     01031325     44       759         HOU
ABQ     02221720    -13       934         STL
ABQ     03011440     13       580         DAL
ABQ     01240905      5       628         SAN
ABQ     01261500      0       628         SAN
ABQ     03261305      0       328         PHX
ABQ     02122000     -5       487         LAS
ABQ     01181005    -12       677         LAX
ABQ     02051840      7       328         PHX
ABQ     01261514     46       580         DAL
ABQ     03171020     -5      1552         MCO
ABQ     01292117      9       580         DAL
ABQ     02132100     54       487         LAS
ABQ     02251130      0       487         LAS
ABQ     03271505    -10       328         PHX
ABQ     03281805     -3       321         TUS
ABQ     02040810     -9       328         PHX
ABQ     02260700     30       677         LAX
ABQ     02221655     12       677         LAX
ALB     01101310    -12       288         BWI
ALB     02050640     19       288         BWI
ALB     01161440    -10      1073         MCO
ALB     02011230    -32      2237         LAS
AMA     03191110     -6       324         DAL
AMA     03062010     -3       324         DAL
AMA     01030950      0       324         DAL
AMA     03281950      5       277         ABQ
...          ...    ...       ...         ...
STL     01251130      3       487         CLE
TPA     01291634     61       197         FLL
TPA     03151535     32       197         FLL
TPA     03180735    -22      1497         ABQ
TPA     01220745     -1       487         MSY
TPA     02152208     65       197         FLL
TPA     03251615     -5       197         FLL
TPA     03301415     -2      1048         MCI
TPA     01161110    -11       612         BNA
TPA     01262055    -10       174         PBI
TPA     03042148     68       842         BWI
TPA     03021630      5       838         IND
TPA     02041155     -8       997         MDW
TPA     02191305     13       180         JAX
TPA     01030740     -2       587         RDU
TPA     02091350     10       197         FLL
TUL     03251220     -6       237         DAL
TUL     02192010      0       453         HOU
TUL     01131030     -3       223         MCI
TUL     03221045     17       237         DAL
TUL     02091222     72       351         STL
TUL     02251315      0       453         HOU
TUL     03140815      2       223         MCI
TUL     02151957    165       237         DAL
TUL     01170615     10       453         HOU
TUS     01081036      8       365         LAS
TUS     03310625      6       451         LAX
TUS     01130750     -6       367         SAN
TUS     01291935     -7       365         LAS
TUS     02250625      5       451         LAX

[1000 rows x 4 columns]

In [31]:
df.sort_values(by='origin')

         date  delay  distance origin destination
386  03201840    -10       328    ABQ         PHX
587  01220705    -10       223    ABQ         ELP
41   02261255      8       628    ABQ         SAN
770  01031325     44       759    ABQ         HOU
280  02221720    -13       934    ABQ         STL
995  03011440     13       580    ABQ         DAL
764  01240905      5       628    ABQ         SAN
515  01261500      0       628    ABQ         SAN
331  03261305      0       328    ABQ         PHX
338  02122000     -5       487    ABQ         LAS
967  01181005    -12       677    ABQ         LAX
748  02051840      7       328    ABQ         PHX
84   01261514     46       580    ABQ         DAL
104  03171020     -5      1552    ABQ         MCO
380  01292117      9       580    ABQ         DAL
377  02132100     54       487    ABQ         LAS
703  02251130      0       487    ABQ         LAS
418  03271505    -10       328    ABQ         PHX
415  03281805     -3       321    ABQ         TUS
932  02040810     -9       328    ABQ         PHX
409  02260700     30       677    ABQ         LAX
717  02221655     12       677    ABQ         LAX
626  01101310    -12       288    ALB         BWI
43   02050640     19       288    ALB         BWI
80   01161440    -10      1073    ALB         MCO
777  02011230    -32      2237    ALB         LAS
408  03191110     -6       324    AMA         DAL
51   03062010     -3       324    AMA         DAL
461  01030950      0       324    AMA         DAL
549  03281950      5       277    AMA         ABQ
..        ...    ...       ...    ...         ...
191  01251130      3       487    STL         CLE
578  01291634     61       197    TPA         FLL
522  03151535     32       197    TPA         FLL
529  03180735    -22      1497    TPA         ABQ
736  01220745     -1       487    TPA         MSY
42   02152208     65       197    TPA         FLL
666  03251615     -5       197    TPA         FLL
98   03301415     -2      1048    TPA         MCI
953  01161110    -11       612    TPA         BNA
427  01262055    -10       174    TPA         PBI
358  03042148     68       842    TPA         BWI
258  03021630      5       838    TPA         IND
366  02041155     -8       997    TPA         MDW
753  02191305     13       180    TPA         JAX
711  01030740     -2       587    TPA         RDU
86   02091350     10       197    TPA         FLL
201  03251220     -6       237    TUL         DAL
83   02192010      0       453    TUL         HOU
92   01131030     -3       223    TUL         MCI
847  03221045     17       237    TUL         DAL
406  02091222     72       351    TUL         STL
44   02251315      0       453    TUL         HOU
321  03140815      2       223    TUL         MCI
580  02151957    165       237    TUL         DAL
949  01170615     10       453    TUL         HOU
421  01081036      8       365    TUS         LAS
508  03310625      6       451    TUS         LAX
642  01130750     -6       367    TUS         SAN
689  01291935     -7       365    TUS         LAS
925  02250625      5       451    TUS         LAX

[1000 rows x 5 columns]

## 分组排名

In [36]:
rnk = df.groupby('origin')['delay'].rank(method='first', ascending=False)
df.assign(rnk=rnk).query('rnk <= 3').sort_values(['origin', 'rnk'])

         date  delay  distance origin destination  rnk
377  02132100     54       487    ABQ         LAS  1.0
84   01261514     46       580    ABQ         DAL  2.0
770  01031325     44       759    ABQ         HOU  3.0
43   02050640     19       288    ALB         BWI  1.0
80   01161440    -10      1073    ALB         MCO  2.0
626  01101310    -12       288    ALB         BWI  3.0
549  03281950      5       277    AMA         ABQ  1.0
461  01030950      0       324    AMA         DAL  2.0
51   03062010     -3       324    AMA         DAL  3.0
831  01121952    100      1162    AUS         RDU  1.0
751  02112055     10       189    AUS         DAL  2.0
266  01061540      3       148    AUS         HOU  3.0
15   03151759     36       283    BDL         BWI  1.0
330  02021755     26       283    BDL         BWI  2.0
663  02021554     13       283    BDL         BWI  3.0
121  02161950     62       321    BHM         MSY  1.0
217  03091929     11       323    BHM         SDF  2.0
730  03071830      3       570    BHM         MDW  3.0
849  02242347    113       588    BNA         BWI  1.0
488  02262340    110       588    BNA         BWI  2.0
424  01291305    104       491    BNA         MCI  3.0
188  02091926     44       335    BOI         RNO  1.0
714  02262045     18       399    BOI         SEA  2.0
205  02181605      0       287    BOI         GEG  3.0
853  02131100     14      1912    BUF         PHX  1.0
132  03041510      7       281    BUF         BWI  2.0
815  03210930      1       281    BUF         BWI  3.0
28   01181812     71       325    BUR         OAK  1.0
53   01241217     22       325    BUR         OAK  2.0
627  03211815     22       369    BUR         PHX  3.0
..        ...    ...       ...    ...         ...  ...
310  03151210     -1       323    SDF         BHM  2.0
654  01061345    110       689    SEA         SLC  1.0
198  03131738     74       564    SEA         RNO  2.0
67   02251805     28       671    SEA         OAK  3.0
483  01181545      3       447    SFO         SAN  1.0
475  01260850     -1       447    SFO         SAN  2.0
835  02121133     99       308    SJC         LAX  1.0
46   01162309     75       621    SJC         PHX  2.0
160  03141109     55       386    SJC         LAS  3.0
270  01200845    135       368    SLC         LAS  1.0
868  03051456     74       368    SLC         LAS  2.0
489  02081630     19       507    SLC         PHX  3.0
410  02252225     60       389    SMF         ONT  1.0
955  01022150     51       480    SMF         SAN  2.0
787  03161943     49       480    SMF         SAN  3.0
402  02241843     15       371    SNA         OAK  1.0
761  03020845     15       342    SNA         SJC  2.0
682  03020745     13       371    SNA         OAK  3.0
884  01121935     62       254    STL         SDF  1.0
452  01201525     45       254    STL         SDF  2.0
261  02131638     44       687    STL         HOU  3.0
358  03042148     68       842    TPA         BWI  1.0
42   02152208     65       197    TPA         FLL  2.0
578  01291634     61       197    TPA         FLL  3.0
580  02151957    165       237    TUL         DAL  1.0
406  02091222     72       351    TUL         STL  2.0
847  03221045     17       237    TUL         DAL  3.0
421  01081036      8       365    TUS         LAS  1.0
508  03310625      6       451    TUS         LAX  2.0
925  02250625      5       451    TUS         LAX  3.0

[174 rows x 6 columns]